name: joinln
description: A new Flutter project for map-first social planning.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  
  # Maps
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  
  # Utilities
  provider: ^6.1.1
  intl: ^0.19.0
  uuid: ^4.2.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # UI
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  country_code_picker: ^3.0.0
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
